name: py

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
      - name: install repo
        run: |
          git clone git@gitlab.com:kicad/libraries/kicad-footprint-generator.git
          cd kicad-footprint-generator
          python3 setup.py
